"""add tenant fields to organizations

Revision ID: ac911447a50f
Revises: ee5b1c60bbf8
Create Date: 2026-03-10 14:58:37.677321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac911447a50f'
down_revision: Union[str, None] = 'ee5b1c60bbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('primary_color', sa.String(length=7), nullable=True, server_default='#1d4ed8'))
    op.add_column('organizations', sa.Column('subscription_plan', sa.String(length=50), nullable=False, server_default='free'))
    op.add_column('organizations', sa.Column('max_users', sa.Integer(), nullable=False, server_default='10'))
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('organizations', 'max_users')
    op.drop_column('organizations', 'subscription_plan')
    op.drop_column('organizations', 'primary_color')
    op.drop_column('organizations', 'logo_url')
    # ### end Alembic commands ###